<a href="https://colab.research.google.com/github/torinunim/practice/blob/practice/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



## Pandas 객체


### Series 객체

### DataFrame 객체

### Index 객체


#### Index 연산



---



## 인덱싱(Indexing)

### Series 인덱싱

### DataFrame 인덱싱


### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

#### 다중 인덱스 생성

#### 인덱싱 및 슬라이싱

#### 다중 인덱스 재정렬

## 데이터 연산

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(0, 10, 5))
s

0    4
1    1
2    4
3    3
4    7
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns=['A', 'B', 'C'])
df

A  B  C
0  4  3  2
1  8  6  5
2  6  0  2

In [ ]:
np.exp(s)

0      54.598150
1       2.718282
2      54.598150
3      20.085537
4    1096.633158
dtype: float64

In [ ]:
np.cos(df * np.pi / 4)

A             B             C
0 -1.000000e+00 -7.071068e-01  6.123234e-17
1  1.000000e+00 -1.836970e-16 -7.071068e-01
2 -1.836970e-16  1.000000e+00  6.123234e-17

In [ ]:
s1 = pd.Series([1, 3, 5, 7, 9], index = [0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index = [1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [ ]:
s1.add(s2,fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                   columns=list('ACD'))
df1

A   C   D
0   5   6   2
1  10  12  19
2  16  17  17

In [ ]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                   columns=list('BAECD'))
df2

B   A   E   C   D
0  16   9   9  19   1
1  12  18   8  17  18
2   6   4  15  19   3
3   8   3   9   7  12
4   7  14  15  19   9

In [ ]:
df1+df2

A   B     C     D   E
0  14.0 NaN  25.0   3.0 NaN
1  28.0 NaN  29.0  37.0 NaN
2  20.0 NaN  36.0  20.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [ ]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0  14.000000  27.555556  25.000000   3.000000  20.555556
1  28.000000  23.555556  29.000000  37.000000  19.555556
2  20.000000  17.555556  36.000000  20.000000  26.555556
3  14.555556  19.555556  18.555556  23.555556  20.555556
4  25.555556  18.555556  30.555556  20.555556  26.555556

### 연산자 범용 함수


#### add()

In [ ]:
a = np.random.randint(1, 10, (3, 3))
a

array([[3, 3, 4],
       [6, 3, 1],
       [3, 1, 1]])

In [ ]:
a + a[0]

array([[6, 6, 8],
       [9, 6, 5],
       [6, 4, 5]])

In [ ]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  3  3  4
1  6  3  1
2  3  1  1

In [ ]:
df + df.iloc[0]

A  B  C
0  6  6  8
1  9  6  5
2  6  4  5

#### sub() / subtract()

In [ ]:
a

array([[3, 3, 4],
       [6, 3, 1],
       [3, 1, 1]])

In [ ]:
a - a[0]

array([[ 0,  0,  0],
       [ 3,  0, -3],
       [ 0, -2, -3]])

In [ ]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  3  0 -3
2  0 -2 -3

In [ ]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  3  0 -3
2  0 -2 -3

In [ ]:
df.subtract(df['B'], axis=0)

A  B  C
0  0  0  1
1  3  0 -2
2  2  0  0

#### mul() / multply()




In [ ]:
a

array([[3, 3, 4],
       [6, 3, 1],
       [3, 1, 1]])

In [ ]:
a * a[1]

array([[18,  9,  4],
       [36,  9,  1],
       [18,  3,  1]])

#### truediv() /  div() / divide() / floordiv()

#### mod()

#### pow()

### 정렬(Sort)

In [ ]:
s = pd.Series(range(5), index=['A', 'D', 'C', 'E', 'B'])
s

A    0
D    1
C    2
E    3
B    4
dtype: int64

In [ ]:
s.sort_index()

A    0
B    4
C    2
D    1
E    3
dtype: int64

In [ ]:
s.sort_values()

A    0
D    1
C    2
E    3
B    4
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                  index=[2, 4, 1, 3],
                  columns=list('BDAC'))
df

B  D  A  C
2  2  2  7  5
4  0  4  7  3
1  7  9  3  2
3  2  5  4  5

In [ ]:
df.sort_index()

B  D  A  C
1  7  9  3  2
2  2  2  7  5
3  2  5  4  5
4  0  4  7  3

In [ ]:
df.sort_index(axis=1)

A  B  C  D
2  7  2  5  2
4  7  0  3  4
1  3  7  2  9
3  4  2  5  5

In [ ]:
df.sort_values(by='A')

B  D  A  C
1  7  9  3  2
3  2  5  4  5
2  2  2  7  5
4  0  4  7  3

In [ ]:
df.sort_values(by=['A', 'C'])

B  D  A  C
1  7  9  3  2
3  2  5  4  5
4  0  4  7  3
2  2  2  7  5

### 순위(Ranking)


In [ ]:
 s= pd.Series([-2, 4, 6, 7, 12, 0, -4])
 s

0    -2
1     4
2     6
3     7
4    12
5     0
6    -4
dtype: int64

In [ ]:
s.rank()

0    2.0
1    4.0
2    5.0
3    6.0
4    7.0
5    3.0
6    1.0
dtype: float64

In [ ]:
s.rank(method='first')

0    2.0
1    4.0
2    5.0
3    6.0
4    7.0
5    3.0
6    1.0
dtype: float64

In [ ]:
s.rank(method='max')

0    2.0
1    4.0
2    5.0
3    6.0
4    7.0
5    3.0
6    1.0
dtype: float64

### 고성능 연산

In [ ]:
nrows, ncols = 10000, 100

## 데이터 결합

### Concat() / Append()

In [ ]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [14]:
def create_df(cols, idx):
  data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
  return pd.DataFrame(data, idx)

In [4]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [9]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [10]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [7]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [8]:
df4 = create_df('CD', [0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [11]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [12]:
import pandas as pd
import numpy as np
pd.concat([df1, df3], keys=['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [15]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [16]:
pd.concat([df5, df6], join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [19]:
df5.append(df6)

AttributeError: 'DataFrame' object has no attribute 'append'

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly